include: package:flutter_lints/flutter.yaml

# Custom analyzer plugins
plugins:
  example_analyzer_plugin:
    path: packages/example_analyzer_plugin
    diagnostics:
      # Enable lint rules explicitly (warning rules are enabled by default)
      todo_comment: true

linter:
  rules:
    # avoid_print: false  # Uncomment to disable the `avoid_print` rule
    # prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule
# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

dcm:
  rules:
    #--------BLoC-------------
    # Crash & leak prevention
    - check-is-not-closed-after-async-gap
    - avoid-existing-instances-in-bloc-provider
    - avoid-instantiating-in-bloc-value-provider
    - avoid-passing-build-context-to-blocs

    # Architectural integrity
    - avoid-bloc-public-methods
    - avoid-bloc-public-fields
    - emit-new-bloc-state-instances
    - avoid-passing-bloc-to-bloc

    # Dart 3+
    - prefer-sealed-bloc-events:
        name-pattern: Event$
    - prefer-sealed-bloc-state:
        name-pattern: State$
    - prefer-immutable-bloc-events:
        name-pattern: Event$
    - prefer-immutable-bloc-state:
        name-pattern: State$

    # Code style
    - prefer-multi-bloc-provider
    - prefer-bloc-extensions
    - avoid-empty-build-when
    - prefer-bloc-event-suffix:
        name-pattern: Event$
        ignore-subclasses: true
    - prefer-bloc-state-suffix:
        name-pattern: State$
        ignore-subclasses: true
    #--------BLoC-------------
